#!/usr/bin/python

import sys
import subprocess

submodules = {
    "balance": "chem-balance"
}

module = submodules[sys.argv[1]]
module = ["python3", module]
args = sys.argv[2:]

if "-" in args:
    index = args.index("-")
    if len(args) > index and args[index+1] == "+":
        sys.stderr.write(
            "WARNING: You can't use '->' in your input without wrapping "
            + "your forumla in quotes. Execution may be unpredictable. If "
            + "you don't want to use quotes, use '=' instead of '->'.\n"
        )

if "--" in args:
    index = args.index("--")
    if len(args) > index and args[index+1] == "+":
        sys.stderr.write(
            "WARNING: You can't use '-->' in your input without wrapping "
            + "your  forumla in quotes. Execution may be unpredictable. If "
            + "you don't want to use quotes, use '=' instead of '-->'.\n"
        )

if sys.argv[1] in submodules:
    sp = subprocess.Popen(module+sys.argv[2:])
    sp.wait()
    
    
